### ISSUE TITLE
Allow user to trade their hand in for a new hand in exchange for losing a point

### ISSUE THREAD

**Issue by nickheidke** [thunderblaster/cards#23]

**Comment by thunderblaster** [comment]
This seems straightforward enough to implement (add a button to the UI, emit 'tradehand' from the client on click, server wipes their hand and calls 'dealwhite' and subtracts a point, emits 'userlist') but I wonder where we put the button on mobile and how we make it clear enough wtf it does.  Maybe a somewhat ambiguous button that launches a modal that is like "Do you want to trade your hand in exchange for losing a point? yes/no"?  The actual UI piece of that would likely be more complicated than the server code/JS.

**Comment by nickheidke** [comment]
This has been implemented as "My cards suck." It issues a prompt to make sure the user knows what they are doing.
