### ISSUE TITLE
End State

### ISSUE THREAD

**Issue by thunderblaster** [thunderblaster/cards#6]
Currently if you manage to exhaust the black deck (time-consuming but possible), it will fail to draw a new black card and... that's it. No error, no victory screen, just appears to freeze in the UI.  An end state should be written in the GUI and the server should send a "gameover" message when certain conditions are met (such as either card deck array exhausted, or perhaps the users could set a point threshold in advance).  Low priority as it's easy to informally treat the game as over whenever you want.

**Comment by nickheidke** [comment]
Might be nice to also have an end state of achieving a certain number of points. Input could be taken at game start for how many points to play to?

**Comment by nickheidke** [comment]
Users are now prompted for a "winning score" at the start of the game. Only the first player in sets the winning score.
