### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by thunderblaster** [thunderblaster/cards#9]
It'd be great to have an extremely rudimentary chat, primarily to just post the link to the Hangouts or Discord or wherever people are talking. This is functionally pretty trivial with socket.io, but the interface will nontrivial as space on mobile is already at a premium, so it would likely need a toggle button and overlay overtop the cards. And then we'd want a badge or icon indicator that new messages exist so users know to look at it. 
Alternatively, we could make one player the king of the room and allow them to set one text field that displays to all users. This would accomplish handling the link without diving into the pitfalls of fullfledged chat. We could make it universally editable to avoid having a room mod/admin as that's one more thing to track and it'd need to be passed if that player dropped.

**Comment by nickheidke** [comment]
In lieu of a full interactive chat, it may be sufficient to allow any player to set a "topic" for the room where a discord link or zoom meeting link could be posted. I do think the game is still best played with a video chat up, I don't think that's replaceable.

**Comment by thunderblaster** [comment]
Fixed by latest merge. I changed some of the CSS to make room for another element on screen and also added Font Awesome and made things slightly prettier than they had been.  @beatsforthemind might be able to further beautify with work on #16

**Comment by thunderblaster** [comment]
I am a moron and this is not complete. The client side exists and is pretty and whatever, but it's not tracked serverside or broadcast to clients. Reopening and I should be able to truly fix tonight.

**Comment by thunderblaster** [comment]
Should be really fixed now.
